### ISSUE TITLE
Does this work with meteor-cordova ?

### ISSUE THREAD

**Issue by cunneen** [4commerce-technologies-AG/meteor-package-environments#4]
Hi, I'm intrigued by your package. From the readme it sounds like it runs on Meteor.startup. 

Are the public settings (Meteor.settings.public.*) clobbered properly when a cordova app is built from meteor? (in other words, can we safely use this package with cordova, and have you tested this?)

Thanks.

**Comment by TomFreudenberg** [comment]
Hi Mike ( @cunneen )

nice to get some feedback that this may usefull for others too.

You are absoultely right, it runs on server side `Meteor.startup()`

See: [env-settings.js#L116](https://github.com/4commerce-technologies-AG/meteor-package-env-settings/blob/master/env-settings.js#L116)

I have not yet (hardly) tested by cordava app but I would be wondering why this shouldn't work. `Meteor.settings.public` is a meteor built-in and you are allowed to attach properties e.g. via `ENV` var per default.

So there is NO client side code ([see packages.js](env-settings.js#L116)) it has to work on cordava as well.

I am currently finishing a new customer app where we used this ourself. I will give some comments when running that on android.

Hope the infos are giving you the right decision.

Tom

**Comment by cunneen** [comment]
Thanks @TomFreudenberg .

**Comment by TomFreudenberg** [comment]
@cunneen Your welcome, nice to know someone is using that stuff but us 👍
